Short read analysis code added

diff --git a/metapointfinder b/metapointfinder
--- a/metapointfinder
+++ b/metapointfinder
@@ -138,15 +138,13 @@ if ! test -f AMRProt-mutation.tsv; then
     wget -nv -c https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/AMRProt-mutation.tsv 1>> databaseprep.log 2>> databaseprep.error
 fi
 
+#prep database
+if ! test -f AMRProt-mutation_underscore_combined.tsv; then
 #replace slashes by underscores
 cat AMRProt-mutation.tsv  |sed 's/\//_/g' > AMRProt-mutation_underscore.tsv
-
 #remove this line and replace class with a file with only the AB class or accession you want to check
 cat AMRProt-mutation_underscore.tsv |cut -f 6 |sort |uniq > class
 cat AMRProt-mutation_underscore.tsv |cut -f 2 |sort |uniq > accession
-
-#prep database
-if ! test -f AMRProt-mutation_underscore_combined.tsv; then
 # this loop combines all the mutations in one line per protein per class. only needs to be done once
 echo "Prepping AMRProt mutation database"
 cat class |while read class ; do
@@ -163,8 +161,9 @@ fi
 #build the diamond database
 
 if ! test -f AMRProt.dmnd; then 
+    cat AMRProt.fa |tr  "\n" "\t" |tr ">" "\n"  |grep mutation |sed 's/^/>/'|tr "\t" "\n" >AMRProt_mutation.fa
     echo "Building AMRProt diamond database"
-    diamond makedb --in AMRProt.fa --db AMRProt 1>> databaseprep.log 2>> databaseprep.error
+    diamond makedb --in AMRProt_mutation.fa --db AMRProt 1>> databaseprep.log 2>> databaseprep.error
 fi
 
 #get the DNA databases
@@ -203,30 +202,32 @@ if ! test -f AMR_DNA-mutation.tsv; then
     mv temp-mutation.tsv AMR_DNA-mutation.tsv
 fi
 
+#prep database
+if ! test -f AMR_DNA_underscore_combined.tsv; then
 #replace slashes by underscores
 cat AMR_DNA-mutation.tsv  |sed 's/\//_/g' |grep -v class> AMR_DNA-mutation_underscore.tsv
 cat AMR_DNA.fa |sed 's/\//_/g'  > AMR_DNA_underscore.fa
-cat AMR_DNA_underscore.fa |tr  "\n" " " |tr ">" "\n" |sed 's/ /	/'|tr -d " " > AMR_DNA_underscore_fa.tsv
-
+cat AMR_DNA_underscore.fa |tr  "\n" " " |tr ">" "\n" |sed 's/ /\t/'|tr -d " " > AMR_DNA_underscore_fa.tsv
 #remove this line and replace class or accession with a file with only the AB class or gene you want to check
 cat AMR_DNA-mutation_underscore.tsv |cut -f 5 |sort |uniq > dna_class
 cat AMR_DNA-mutation_underscore.tsv |cut -f 1 |sort |uniq > dna_accession
-
-#prep database
-if ! test -f AMR_DNA_underscore_combined.tsv; then
 # this loop combines all the mutations in one line per protein per class. only needs to be done once
 echo "Prepping AMR_DNA mutation database"
 cat dna_class |while read class ; do
     cat dna_accession |while read accession; do
-	cat AMR_DNA-mutation_underscore.tsv |cut -f 1,3,5 |grep -w "$class" |grep -w "$accession" |sort -nk 1 |while read accession mutation class2 ; do
-	    sequence=`cat AMR_DNA_underscore_fa.tsv |grep "$accession" |cut -f 2`
-	    mutation_cleaned=`echo "$mutation" |cut -f 2 -d _`
-	    changes_str=`echo "$mutation_cleaned"",""$changes_str"`
-	    echo "$class" "$accession" "$sequence" "$changes_str"
-	done |sed 's/,$//' |tail -n 1|tr " " "\t" >> AMR_DNA_underscore_combined.tsv
+        cat AMR_DNA-mutation_underscore.tsv |cut -f 1,2,3,5 |grep -w "$class" |grep -w "$accession" |sort -nk 1 |while read accession position mutation_original class2 ; do
+            sequence=`cat AMR_DNA_underscore_fa.tsv |grep "$accession" |cut -f 2`
+            mutation_cleaned=`echo "$mutation_original" |cut -f 2 -d _`
+            baseright=`echo $mutation_cleaned |tr '0-9' '\t'|tr -s "\t"|tr -d "-" |cut -f 2`
+            baseleft=`echo $mutation_cleaned  |tr '0-9' '\t'|tr -d "-" |cut -f 1`
+            mutation="${baseleft}${position}${baseright}"
+            changes_str=`echo "$mutation"",""$changes_str"`
+            echo "$class" "$accession" "$sequence" "$changes_str" |sed 's/del/-/g'
+        done |sed 's/,$//' |tail -n 1|tr " " "\t" >> AMR_DNA_underscore_combined.tsv
     done
 done
 fi
+
 
 #build the kma database
 
@@ -253,7 +254,7 @@ cat "$database"/AMR_DNA-mutation_underscore.tsv |cut -f 1 |sort |uniq > dna_acce
 
 #align the reads against proteins
 echo "Aligning reads to proteins using diamond blastx"
-diamond blastx -d "$database"/AMRProt -q "$sample".fastq -o "$sample".prot.hits.txt -F 15 --range-culling -k1 --range-cover 5 --iterate --id 80 --subject-cover 90 --masking 0 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore full_sseq qseq_translated 1>> "$sample".log 2>> "$sample".error
+diamond blastx -d "$database"/AMRProt -q "$sample".fastq -o "$sample".prot.hits.txt -F 15 --range-culling -k1 --range-cover 5 --iterate --id 80 --masking 0 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore full_sseq qseq_translated 1>> "$sample".log 2>> "$sample".error
 
 # make the input for R
 echo "Parsing diamond output"
@@ -274,16 +275,21 @@ rm updated_table_with_scores_and_mutations.tsv
 
 #align the reads against DNA
 echo "Aligning reads to genes using kma"
-kma -t -bcNano -hmm -ont -t_db "$database"/AMR_DNA_underscore -i "$sample".fastq -o "$sample" -ID 80 -t 16 -nc -na 1>> "$sample".log 2>> "$sample".error
+kma -t -bcNano -hmm -ont -t_db "$database"/AMR_DNA_underscore -i "$sample".fastq -o "$sample" -t 16 -nc -na 1>> "$sample".log 2>> "$sample".error
 
-# make the input for R. Hack to remove too short reads. KMA lengthfilter (-mrc 0.9) does not always work properly.
+# we delete the temp fastq file
+rm "$sample".fastq
+
+# make the input for R. leftover code from hack to remove too short nanopore reads as KMA lengthfilter (-mrc 0.9) does not always work properly. now removed for illumina 
 echo "Parsing KMA output"
 echo "class	gene	read	reference	target	changes_str" >$sample.dna.input.tsv
 zcat $sample.frag.gz |cut -f 1,6,7 |cut -f 1 -d " " |while read target accession read ; do 
     cat $database/AMR_DNA_underscore_combined.tsv |grep $accession |while read class accession reference changes; do
 	echo $class $accession $read $reference $target $changes
     done
-done | tr " " "\t" |awk 'length($5) >= 0.9 * length($4)' >>$sample.dna.input.tsv
+#done | tr " " "\t" |awk 'length($5) >= 0.9 * length($4)' >>$sample.dna.input.tsv
+done | tr " " "\t"  >>$sample.dna.input.tsv
+
 
 #run the R script. Too lazy to do argument parsing with R
 echo "Scoring DNA mutations"
@@ -299,17 +305,19 @@ rm updated_table_with_scores_and_mutations.tsv
 
 #quick collation of results
 cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v None|cut -f 2 |grep -v gene |sort|uniq >gene
-echo class WT R |tr " " "\t" >"$sample".class.prot.summary.txt
-echo gene WT R |tr " " "\t" >"$sample".gene.prot.summary.txt
+echo class WT R UNKNOWN |tr " " "\t" >"$sample".class.prot.summary.txt
+echo gene WT R UNKNOWN  |tr " " "\t" >"$sample".gene.prot.summary.txt
 
 cat class | while read class ; do
-    WT=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|cut -f 7 |grep -w 0 |wc -l`
-    R=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|cut -f 7 |grep -v -w 0 |wc -l`
-    echo $class $WT $R |tr " " "\t" >>"$sample".class.prot.summary.txt
+    WT=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|cut -f 10 |grep -w Wildtype  |wc -l`
+     R=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|cut -f 10 |grep -w Resistant |wc -l`
+    NA=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|cut -f 10 |grep -w Unknown   |wc -l`
+    echo $class $WT $R $NA |tr " " "\t" >>"$sample".class.prot.summary.txt
     cat gene |while read gene ; do
-	WT=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|fgrep "$gene" |cut -f 7 |grep -w 0 |wc -l`
-	R=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|fgrep "$gene" |cut -f 7 |grep -v -w 0 |wc -l`
-	echo "$class"."$gene" $WT $R |tr " " "\t" |grep -v "0	0">>"$sample".gene.prot.summary.txt
+	WT=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|fgrep "$gene" |cut -f 10 |grep -w Wildtype  |wc -l`
+	 R=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|fgrep "$gene" |cut -f 10 |grep -w Resistant |wc -l`
+	NA=`cat "$sample".prot.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|fgrep "$gene" |cut -f 10 |grep -w Unknown   |wc -l`
+	echo "$class"."$gene" $WT $R $NA |tr " " "\t" |grep -v "0	0	0">>"$sample".gene.prot.summary.txt
     done
 done
 
@@ -318,7 +326,7 @@ if test -f "$sample.prot.updated_table_with_scores_and_mutations.tsv"; then
     echo "Protein read classification output (WT/R) can be found in the file "$output"/"$sample".prot.updated_table_with_scores_and_mutations.tsv"
 else
     echo "Protein read classification output not generated. Something went wrong"
-    exit 1
+    #return 1
 fi
 
 if test -f ""$sample".class.prot.summary.txt"; then
@@ -327,22 +335,24 @@ if test -f ""$sample".class.prot.summary.txt"; then
     echo
 else
     echo "Protein summary output not generated. Something went wrong"
-    exit 1
+    #return 1
 fi
 
 #quick collation of results
-cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v None|cut -f 2 |grep -v gene |sort|uniq >gene
-echo class WT R |tr " " "\t" >"$sample".class.dna.summary.txt
-echo gene WT R |tr " " "\t" >"$sample".gene.dna.summary.txt
+cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v None|cut -f 2 |grep -v gene |sort|uniq >dna_gene
+echo class WT R UNKNOWN |tr " " "\t" >"$sample".class.dna.summary.txt
+echo gene WT R UNKNOWN  |tr " " "\t" >"$sample".gene.dna.summary.txt
 
 cat class | while read class ; do
-    WT=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|cut -f 7 |grep -w 0 |wc -l`
-    R=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|cut -f 7 |grep -v -w 0 |wc -l`
-    echo $class $WT $R |tr " " "\t" >>"$sample".class.dna.summary.txt
-    cat gene |while read gene ; do
-	WT=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|fgrep "$gene" |cut -f 7 |grep -w 0 |wc -l`
-	R=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep "$class"|fgrep "$gene" |cut -f 7 |grep -v -w 0 |wc -l`
-	echo "$class"."$gene" $WT $R |tr " " "\t" |grep -v "0	0">>"$sample".gene.dna.summary.txt
+    WT=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|cut -f 10 |grep -w Wildtype  |wc -l`
+     R=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|cut -f 10 |grep -w Resistant |wc -l`
+    NA=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|cut -f 10 |grep -w Unknown   |wc -l`
+    echo $class $WT $R $NA |tr " " "\t" >>"$sample".class.dna.summary.txt
+    cat dna_gene |while read dna_gene ; do
+	WT=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|fgrep "$dna_gene" |cut -f 10 |grep -w Wildtype  |wc -l`
+	 R=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|fgrep "$dna_gene" |cut -f 10 |grep -w Resistant |wc -l`
+	NA=`cat "$sample".dna.updated_table_with_scores_and_mutations.tsv |grep -v class |grep -w "$class"|fgrep "$dna_gene" |cut -f 10 |grep -w Unknown   |wc -l`
+	echo "$class"."$dna_gene" $WT $R $NA |tr " " "\t" |grep -v "0	0	0">>"$sample".gene.dna.summary.txt
     done
 done
 
@@ -352,7 +362,7 @@ if test -f ""$sample".dna.updated_table_with_scores_and_mutations.tsv"; then
     echo "DNA read classification output (WT/R) can be found in the file "$output"/"$sample".dna.updated_table_with_scores_and_mutations.tsv"
 else
     echo "DNA read classification output not generated. Something went wrong"
-    exit 1
+    #return 1
 fi
 
 if test -f ""$sample".class.dna.summary.txt"; then
@@ -362,5 +372,5 @@ if test -f ""$sample".class.dna.summary.txt"; then
     exit 0
 else
     echo "DNA summary output not generated. Something went wrong"
-    exit 1
+    #return 1
 fi
